[package]
name = "riscv-slic"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-atomic = { version = "1.4", default-features = false, features = ["require-cas"] }
heapless = "0.7.0"
riscv-peripheral ={ git = "https://github.com/romancardenas/riscv-peripheral.git", branch = "main" }
riscv-slic-macros = { path = "../riscv-slic-macros" }

[features]
msoft = [] # do not enable this feature directly. Use one of the *-backend features instead
ssoft = [] # do not enable this feature directly. Use one of the *-backend features instead

clint-backend = ["msoft", "riscv-slic-macros/clint-backend"] # enable this feature to use the CLINT peripheral as SWI backend
ssoft-backend = ["ssoft", "riscv-slic-macros/ssoft-backend"] # enable this feature to use supervisor-level software interrupts as SWI backend

unsafe-assume-single-core = ["portable-atomic/unsafe-assume-single-core"] # enable this feature for single-core systems with no atomic support
critical-section = ["portable-atomic/critical-section"] # enable this feature for systems with no atomic support that implement critical-section
