[package]
name = "riscv-slic"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.0"
riscv = {git = "https://github.com/rust-embedded/riscv.git", branch = "master"}
riscv-slic-macros = {path = "../riscv-slic-macros"}

[features]
exti-plic = ["riscv-slic-macros/exti-plic", "riscv/plic"]
swi-clint = ["riscv-slic-macros/swi-clint"]
