[package]
name = "riscv-slic"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-polyfill = {git = "https://github.com/romancardenas/atomic-polyfill.git", branch = "main"}
heapless = "0.7.0"
riscv = {git = "https://github.com/rust-embedded/riscv.git", branch = "master"}
riscv-slic-macros = {path = "../riscv-slic-macros"}

[features]
force-atomic-polyfill = ["atomic-polyfill/force-polyfill"]
exti-plic = ["riscv-slic-macros/exti-plic", "riscv/plic"]
swi-clint = ["riscv-slic-macros/swi-clint"]
