[target.'cfg(all(any(target_arch = "riscv32", target_arch = "riscv64"), target_os = "none"))']
runner = "riscv64-unknown-elf-gdb -q -x gdb_init"
# runner = "probe-run --chip fe310-g002 --verbose"
rustflags = [
  "-C", "link-arg=-Thifive1-link.x",
]

[build]
target = "riscv32imc-unknown-none-elf"
