name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:
          - riscv32i-unknown-none-elf
          - riscv32imc-unknown-none-elf
          - riscv32imac-unknown-none-elf
          - riscv64gc-unknown-linux-gnu
          - riscv64gc-unknown-none-elf
        cargo_flags:
          - "--no-default-features"
          - "--features=swi-clint"
          - "--features=exti-plic,swi-clint"

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Install Rust target
      run: rustup target install --toolchain=${{ matrix.toolchain }} ${{ matrix.target }} 
    - name: Install riscv gcc
      run: sudo apt-get update && sudo apt-get install -y gcc-riscv64-unknown-elf
    - name: Build
      run: cargo check --target ${{ matrix.target }} ${{ matrix.cargo_flags }}
